# Generated by Django 3.2.9 on 2021-11-19 14:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_to_processing_db',
            field=models.BooleanField(default=False, verbose_name='согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона, например, +79999999999', max_length=128, null=True, region=None, verbose_name='Мобильный телефон'),
        ),
    ]
