# Generated by Django 3.2.9 on 2021-11-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basecategoryprice',
            table=None,
        ),
    ]
