# Generated by Django 3.2.9 on 2021-11-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_warehouse_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='storage.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_order', to='storage.order', verbose_name='Основной заказ'),
        ),
    ]
