# Generated by Django 3.2.9 on 2021-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20211119_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREORDER', 'Не оплачен'), ('ORDER', 'Оплачен'), ('DONE', 'Завершён')], default='PREORDER', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
